spring:
  application:
    name: ddd-modulith-boundaries
  datasource:
    url: jdbc:h2:mem:ddd-modulith-boundaries;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
