package exposed.example.springboot.aot

import io.bluetape4k.logging.KLogging
import org.amshove.kluent.shouldBeEmpty
import org.amshove.kluent.shouldBeEqualTo
import org.amshove.kluent.shouldNotBeNull
import org.jetbrains.exposed.v1.core.DatabaseConfig
import org.jetbrains.exposed.v1.spring.boot.DatabaseInitializer
import org.jetbrains.exposed.v1.spring.boot.autoconfigure.ExposedAutoConfiguration
import org.jetbrains.exposed.v1.spring.transaction.SpringTransactionManager
import org.junit.jupiter.api.Test
import org.springframework.beans.factory.getBean
import org.springframework.boot.autoconfigure.AutoConfigurations
import org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
import org.springframework.boot.test.context.runner.ApplicationContextRunner

/**
 * Spring Boot AoT (Ahead-of-Time) 컴파일 호환성을 [ApplicationContextRunner]로 검증합니다.
 *
 * [ApplicationContextRunner]는 전체 서버를 시작하지 않고 Spring 컨텍스트 구성을 경량으로 테스트하는
 * AoT 친화적인 방법입니다. 자동 구성(Auto-configuration)이 올바르게 동작하는지 빠르게 검증할 수 있습니다.
 *
 * 이 테스트 패턴은 다음과 같은 장점이 있습니다:
 * - `@SpringBootTest` 없이 실행되므로 빠르고 가볍습니다
 * - AoT 컴파일 시 Bean 생성 방식과 동일하게 동작합니다
 * - `proxyBeanMethods = false` 환경에서도 정상 동작합니다
 */
class ExposedAutoConfigurationAotTest {

    companion object: KLogging()

    /**
     * Exposed 자동 구성을 검증하는 기본 [ApplicationContextRunner].
     *
     * DDL 자동 생성은 비활성화하여 [DatabaseInitializer] 빈이 생성되지 않도록 합니다.
     */
    private val contextRunner = ApplicationContextRunner()
        .withConfiguration(
            AutoConfigurations.of(
                DataSourceAutoConfiguration::class.java,
                ExposedAutoConfiguration::class.java,
            )
        )
        .withPropertyValues(
            "spring.datasource.url=jdbc:h2:mem:aot-runner-test;DB_CLOSE_DELAY=-1",
            "spring.datasource.driver-class-name=org.h2.Driver",
            "spring.exposed.generate-ddl=false",
            "spring.exposed.show-sql=true",
        )

    @Test
    fun `SpringTransactionManager 빈이 자동으로 구성되어야 한다`() {
        contextRunner.run { context ->
            context.getBean<SpringTransactionManager>().shouldNotBeNull()
        }
    }

    @Test
    fun `generate-ddl=false 이면 DatabaseInitializer 빈이 생성되지 않아야 한다`() {
        contextRunner.run { context ->
            context.getBeansOfType(DatabaseInitializer::class.java).shouldBeEmpty()
        }
    }

    /**
     * NOTE: [DatabaseInitializer] 빈은 ApplicationContextRunner의 제한된 컨텍스트에서는 생성되지 않습니다.
     * [DatabaseInitializer]는 전체 @SpringBootApplication 컨텍스트에서 [Table] 빈을 스캔한 후 생성됩니다.
     * 이 동작은 [ExposedAutoConfigurationTestAutoGenerateDDL]의 @SpringBootTest 기반 테스트에서 검증합니다.
     */
    @Test
    fun `generate-ddl=true 이면 show-sql 속성이 정상적으로 반영되어야 한다`() {
        contextRunner
            .withPropertyValues(
                "spring.exposed.generate-ddl=true",
                "spring.exposed.show-sql=true",
            )
            .run { context ->
                context.getBean<SpringTransactionManager>().shouldNotBeNull()
            }
    }

    @Test
    fun `커스텀 DatabaseConfig 빈을 등록하면 자동 구성 기본값을 재정의할 수 있다`() {
        contextRunner
            .withBean(
                "customDatabaseConfig",
                DatabaseConfig::class.java,
                { DatabaseConfig { maxEntitiesToStoreInCachePerEntity = 250 } }
            )
            .run { context ->
                val config = context.getBean<DatabaseConfig>()
                config.maxEntitiesToStoreInCachePerEntity shouldBeEqualTo 250
            }
    }
}
