server:
    port: 8080
    compression:
        enabled: true

    tomcat:
        threads:
            max: 200
            min-spare: 20

    shutdown: graceful  # WebServer Graceful shutdown (https://www.baeldung.com/spring-boot-web-server-shutdown)

spring:
    aot:
        enabled: true

    application:
        name: Spring MVC with Exposed

    exposed:
        generate-ddl: false
        show-sql: false

    profiles:
        active: postgres        # postgres | h2

    jackson:
        serialization:
            indent-output: true
    lifecycle:
        timeout-per-shutdown-phase: 10s     # Graceful Shutdown 시간


management:
    endpoints:
        web:
            exposure:
                include: "*"
    endpoint:
        health:
            show-details: always

    metrics:
        tags:
            application: ${spring.application.name}
        distribution:
            percentiles-histogram:
                http.server.requests: true
                resilience4j.circuitbreaker.calls: true
